services:
  - type: web
    name: echospace
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn EchoSpace.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: echospace-db
          property: connectionString
      - key: AI_PROVIDER
        value: mock
      - key: OPENAI_API_KEY
        sync: false
