# Generated by Django 4.2.29 on 2026-03-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='dashscope_session_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
